parameters:
    lamudi_use_case.container.class: Lamudi\UseCaseBundle\Container\UseCaseContainer
    lamudi_use_case.request.resolver.class: Lamudi\UseCaseBundle\Request\RequestResolver

    lamudi_angi_client.default_input_type: default
    lamudi_angi_client.default_input_options: []
    lamudi_angi_client.default_output_type: default
    lamudi_angi_client.default_output_options: []

services:
    lamudi_use_case.container:
        class: "%lamudi_use_case.container.class%"
        calls:
            - ["setDefaultInputProcessor", ["%lamudi_angi_client.default_input_type%", "%lamudi_angi_client.default_input_options%"]]
            - ["setDefaultResponseProcessor", ["%lamudi_angi_client.default_output_type%", "%lamudi_angi_client.default_output_options%"]]

    lamudi_use_case.request.resolver:
        class: "%lamudi_use_case.request.resolver.class%"

    lamudi_use_case.form_input_processor:
        class: Lamudi\UseCaseBundle\Request\Processor\FormInputProcessor
        arguments: ["@form.factory"]
        tags:
            - { name: use_case_input_processor, alias: form }

    lamudi_use_case.input_processor.http:
        class: Lamudi\UseCaseBundle\Request\Processor\HttpInputProcessor
        tags:
            - { name: use_case_input_processor, alias: http }

    lamudi_use_case.input_processor.json_body:
        class: Lamudi\UseCaseBundle\Request\Processor\JsonInputProcessor
        arguments: ["@serializer.encoder.json"]
        tags:
            - { name: use_case_input_processor, alias: json }


    lamudi_use_case.processor.twig_response_processor:
        class: Lamudi\UseCaseBundle\Response\Processor\TwigRenderer
        arguments: ["@?templating"]
        calls:
            - ["setFormFactory", ["@form.factory"]]
        tags:
            - { name: use_case_response_processor, alias: twig }

    lamudi_use_case.json_response_processor:
        class: Lamudi\UseCaseBundle\Response\Processor\JsonRenderer
        arguments: ["@serializer"]
        tags:
            - { name: use_case_response_processor, alias: json }
