parameters:
    lamudi_use_case.request_factory.class: Lamudi\UseCaseBundle\Factory\UseCaseRequestFactory
    lamudi_use_case.request.resolver.class: Lamudi\UseCaseBundle\Factory\RequestResolver
    lamudi_use_case.request.normalizer.class: Lamudi\UseCaseBundle\Factory\RequestNormalizer
    lamudi_use_case.request.initializer.class: Lamudi\UseCaseBundle\Factory\RequestInitializer
    lamudi_use_case.use_case_handler.class: Lamudi\UseCaseBundle\Handler\HttpJsonUseCaseHandler

services:
    lamudi_use_case.container:
        class: "%lamudi_use_case.use_case_handler.class%"
        arguments: ["@serializer.encoder.json"]

    lamudi_use_case.request_factory:
        class: "%lamudi_use_case.request_factory.class%"
        arguments: ["@lamudi_use_case.request.resolver", "@lamudi_use_case.request.normalizer", "@lamudi_use_case.request.initializer"]

    lamudi_use_case.request.resolver:
        class: "%lamudi_use_case.request.resolver.class%"

    lamudi_use_case.request.normalizer:
        class: "%lamudi_use_case.request.normalizer.class%"

    lamudi_use_case.request.initializer:
        class: "%lamudi_use_case.request.initializer.class%"

    lamudi_use_case.use_case_handler:
        class: "%lamudi_use_case.use_case_handler.class%"
        arguments: ["@serializer.encoder.json"]
