parameters:
    lamudi_use_case.executor.class: Lamudi\UseCaseBundle\Execution\UseCaseExecutor
    lamudi_use_case.context_resolver.class: Lamudi\UseCaseBundle\Execution\UseCaseContextResolver
    lamudi_use_case.request_resolver.class: Lamudi\UseCaseBundle\UseCase\RequestResolver
    lamudi_use_case.container.use_case.class: Lamudi\UseCaseBundle\Container\DelegatingContainer
    lamudi_use_case.container.input_processor.class: Lamudi\UseCaseBundle\Container\Container
    lamudi_use_case.container.response_processor.class: Lamudi\UseCaseBundle\Container\Container

    lamudi_use_case.default_context: default
    lamudi_use_case.contexts: []

services:

    ##################################
    # CORE SERVICES
    ##################################
    lamudi_use_case.executor:
        class: "%lamudi_use_case.executor.class%"
        arguments:
            - "@lamudi_use_case.container.use_case"
            - "@lamudi_use_case.context_resolver"

    lamudi_use_case.context_resolver:
        class: "%lamudi_use_case.context_resolver.class%"
        arguments: ["@lamudi_use_case.container.input_processor", "@lamudi_use_case.container.response_processor"]

    lamudi_use_case.container.use_case:
        class: "%lamudi_use_case.container.use_case.class%"
        arguments: ["@service_container"]

    lamudi_use_case.container.input_processor:
        class: "%lamudi_use_case.container.input_processor.class%"

    lamudi_use_case.container.response_processor:
        class: "%lamudi_use_case.container.response_processor.class%"

    lamudi_use_case.request_resolver:
        class: "%lamudi_use_case.request_resolver.class%"

    ##################################
    # INPUT PROCESSORS
    ##################################
    lamudi_use_case.input_processor.array:
        class: Lamudi\UseCaseBundle\Processor\Input\ArrayInputProcessor
        tags:
            - { name: use_case_input_processor, alias: array }

    lamudi_use_case.input_processor.composite:
        class: Lamudi\UseCaseBundle\Processor\Input\CompositeInputProcessor
        arguments: ["@lamudi_use_case.container.input_processor"]
        tags:
            - { name: use_case_input_processor, alias: composite }

    lamudi_use_case.input_processor.form:
        class: Lamudi\UseCaseBundle\Processor\Input\FormInputProcessor
        arguments: ["@form.factory"]
        tags:
            - { name: use_case_input_processor, alias: form }

    lamudi_use_case.input_processor.http:
        class: Lamudi\UseCaseBundle\Processor\Input\HttpInputProcessor
        tags:
            - { name: use_case_input_processor, alias: http }

    lamudi_use_case.input_processor.json_body:
        class: Lamudi\UseCaseBundle\Processor\Input\JsonInputProcessor
        arguments: ["@serializer.encoder.json"]
        tags:
            - { name: use_case_input_processor, alias: json }

    ##################################
    # RESPONSE PROCESSORS
    ##################################
    lamudi_use_case.processor.response_processor.composite:
        class: Lamudi\UseCaseBundle\Processor\Response\CompositeResponseProcessor
        arguments: ["@lamudi_use_case.container.response_processor"]
        tags:
            - { name: use_case_response_processor, alias: composite }

    lamudi_use_case.processor.response_processor.identity:
        class: Lamudi\UseCaseBundle\Processor\Response\IdentityResponseProcessor
        tags:
            - { name: use_case_response_processor, alias: identity }

    lamudi_use_case.processor.response_processor.twig:
        class: Lamudi\UseCaseBundle\Processor\Response\TwigRenderer
        arguments: ["@?templating", "@form.factory"]
        tags:
            - { name: use_case_response_processor, alias: twig }

    lamudi_use_case.response_processor.json:
        class: Lamudi\UseCaseBundle\Processor\Response\JsonRenderer
        arguments: ["@serializer"]
        tags:
            - { name: use_case_response_processor, alias: json }
