parameters:
    lamudi_use_case.container.class: Lamudi\UseCaseBundle\Container\UseCaseContainer
    lamudi_use_case.request.resolver.class: Lamudi\UseCaseBundle\Factory\RequestResolver

    lamudi_angi_client.default_input_type: default
    lamudi_angi_client.default_input_options: []
    lamudi_angi_client.default_output_type: default
    lamudi_angi_client.default_output_options: []

services:
    lamudi_use_case.container:
        class: "%lamudi_use_case.container.class%"
        arguments: ["@annotations.reader", "@lamudi_use_case.request.resolver"]
        calls:
            - ["setDefaultInputConverter", ["%lamudi_angi_client.default_input_type%", "%lamudi_angi_client.default_input_options%"]]
            - ["setDefaultResponseProcessor", ["%lamudi_angi_client.default_output_type%", "%lamudi_angi_client.default_output_options%"]]

    lamudi_use_case.request.resolver:
        class: "%lamudi_use_case.request.resolver.class%"
