parameters:
    lamudi_use_case.executor.class: Lamudi\UseCaseBundle\Container\UseCaseExecutor
    lamudi_use_case.context_resolver.class: Lamudi\UseCaseBundle\Container\UseCaseContextResolver
    lamudi_use_case.request_resolver.class: Lamudi\UseCaseBundle\Request\RequestResolver
    lamudi_use_case.container.use_case.class: Lamudi\UseCaseBundle\Container\DelegatingContainer
    lamudi_use_case.container.input_processor.class: Lamudi\UseCaseBundle\Container\Container
    lamudi_use_case.container.response_processor.class: Lamudi\UseCaseBundle\Container\Container

    lamudi_angi_client.default_input_type: default
    lamudi_angi_client.default_input_options: []
    lamudi_angi_client.default_output_type: default
    lamudi_angi_client.default_output_options: []

services:

    ##################################
    # CORE SERVICES
    ##################################
    lamudi_use_case.executor:
        class: "%lamudi_use_case.executor.class%"
        arguments:
            - "@lamudi_use_case.container.use_case"
            - "@lamudi_use_case.context_resolver"

    lamudi_use_case.context_resolver:
        class: "%lamudi_use_case.context_resolver.class%"
        arguments: ["@lamudi_use_case.container.input_processor", "@lamudi_use_case.container.response_processor"]

    lamudi_use_case.container.use_case:
        class: "%lamudi_use_case.container.use_case.class%"
        arguments: ["@service_container"]

    lamudi_use_case.container.input_processor:
        class: "%lamudi_use_case.container.input_processor.class%"

    lamudi_use_case.container.response_processor:
        class: "%lamudi_use_case.container.response_processor.class%"

    lamudi_use_case.request_resolver:
        class: "%lamudi_use_case.request_resolver.class%"

    ##################################
    # INPUT PROCESSORS
    ##################################
    lamudi_use_case.input_processor.default:
        class: Lamudi\UseCaseBundle\Request\Processor\DefaultInputProcessor
        tags:
            - { name: use_case_input_processor, alias: default }

    lamudi_use_case.input_processor.form:
        class: Lamudi\UseCaseBundle\Request\Processor\FormInputProcessor
        arguments: ["@form.factory"]
        tags:
            - { name: use_case_input_processor, alias: form }

    lamudi_use_case.input_processor.http:
        class: Lamudi\UseCaseBundle\Request\Processor\HttpInputProcessor
        tags:
            - { name: use_case_input_processor, alias: http }

    lamudi_use_case.input_processor.json_body:
        class: Lamudi\UseCaseBundle\Request\Processor\JsonInputProcessor
        arguments: ["@serializer.encoder.json"]
        tags:
            - { name: use_case_input_processor, alias: json }

    ##################################
    # RESPONSE PROCESSORS
    ##################################
    lamudi_use_case.processor.response_processor.default:
        class: Lamudi\UseCaseBundle\Response\Processor\IdentityResponseProcessor
        tags:
            - { name: use_case_response_processor, alias: default }

    lamudi_use_case.processor.response_processor.twig:
        class: Lamudi\UseCaseBundle\Response\Processor\TwigRenderer
        arguments: ["@?templating"]
        calls:
            - ["setFormFactory", ["@form.factory"]]
        tags:
            - { name: use_case_response_processor, alias: twig }

    lamudi_use_case.response_processor.json:
        class: Lamudi\UseCaseBundle\Response\Processor\JsonRenderer
        arguments: ["@serializer"]
        tags:
            - { name: use_case_response_processor, alias: json }
